// ═══════════════════════════════════════════════════════
// dados.js — Lençóis Trekking
// Fonte única de verdade para passeios e hospedagens.
// Edite APENAS este arquivo para atualizar preços e dados.
// ═══════════════════════════════════════════════════════

const LOGO = "https://drive.google.com/thumbnail?id=1WxYc1wY2unzoHDr2quB3eJwQDK-GgzRP&sz=h80";

const ROT = [
  {id:1,nomeEn:"Mosquito Waterfall, Devil's Pool, and Pai Inacio Hill",nome:"Cachoeira do Mosquito, Poço do Diabo e Morro do Pai Inácio",pt:"Saímos de Lençóis por 40 minutos de carro até a entrada da Cachoeira do Mosquito. Fazemos uma trilha curta até a queda e após o banho almoçamos no restaurante da fazenda do Mosquito. Depois seguimos para o Poço do Diabo, um dos maiores poços da Chapada Diamantina. No final do dia, vemos o pôr do sol no Morro do Pai Inácio.\nSaída: 9h | Retorno: 18:30h",en:"We depart from Lençóis and drive for 40 minutes to the entrance of the Mosquito Waterfall. We'll take a short trail down to the waterfall, where we'll enjoy a refreshing swim. Afterward, we'll have lunch at the Mosquito Farm's restaurant. Then we continue by car to Devil's Pool, one of the largest natural swimming spots in the Chapada Diamantina. To end the day, we'll watch the sunset at the iconic Pai Inácio Hill.\nDeparture: 9:00 AM\nReturn: 6:30 PM",taxa:70,fotos:["1Rcqtutp8jzb1eWkGW0UdZ8Pnx3L7FvBI","1Bg3zY_N9kEngAe1FtBAYKsVEu3c0fjgL"],c4:200,c8:400,ag:{3:580,4:580,5:700,6:780,7:1160,8:1160,9:1280,10:1400,11:1480,12:1560,13:1740,14:1740,15:1740,16:1740}},
  {id:2,nomeEn:"Lapa Doce Cave + Pratinha Farm",nome:"Gruta da Lapa Doce + Fazenda Pratinha",pt:"Sairemos de Lençóis por 2 horas até a Gruta da Lapa Doce, onde caminharemos por 1 hora dentro da gruta observando estalactites e estalagmites. Em seguida, 20 minutos de carro até a Fazenda Pratinha, um lençol freático de água cristalina em meio ao sertão baiano.\nSaída: 8:30h | Retorno: 17:30h | Total: 2km",en:"We leave Lençóis for a 2-hour drive to Lapa Doce Cave, where we'll walk for about an hour inside the cave, admiring stalactites and stalagmites. Then we drive 20 minutes to Pratinha Farm, a crystalline spring in the middle of the dry northeastern backlands.\nDeparture: 8:30 AM\nReturn: 5:30 PM\nTotal hike: 2 km",taxa:146,fotos:["1_r97pHhdRYaY82Qe0KDnuEYoM3SixJv7","1o4sRe7M4fuVfyTROW6eKPfYx91lb3FNM"],c4:200,c8:400,ag:{3:530,4:530,5:700,6:730,7:1060,8:1060,9:1230,10:1400,11:1430,12:1460,13:1590,14:1590,15:1590,16:1590}},
  {id:3,nomeEn:"Buracão + Fumacinha + Poços",nome:"Buracão + Fumacinha + Poços",pt:"Saída de Lençóis às 6am por 4 horas de carro até Ibicoara. Nadamos em uma fenda mágica para chegar na Cachoeira do Buracão (90m). 2º dia: trilha técnica até a Fumacinha (18km, avançado). 3º dia: Poço Encantado e Poço Azul.",en:"We leave Lençóis at 6:00 AM and drive for 4 hours to the town of Ibicoara, in the south of the National Park. To reach the majestic 90-meter-high Buracão Waterfall, we'll swim through a magical canyon (life jackets provided). For thrill-seekers, it's possible to rappel the full 90 meters down the waterfall. We overnight in Ibicoara.\nOn Day 2, we hike to Fumacinha Waterfall, hidden in a natural chapel-like canyon. The technical trail is 18 km (round trip) and considered advanced difficulty. We overnight in the town of Mucugê.\nOn Day 3, we visit Poço Encantado and Poço Azul, with their stunning crystal-clear waters.\nReturn to Lençóis: around 5:00 PM",taxa:0,fotos:[],c4:850,c8:1700,ag:{3:2150,4:2150,5:2850,6:2850,7:5700,8:5700,9:5000,10:5700,11:5700,12:5700,13:6450,14:6450,15:6450,16:6450}},
  {id:4,nomeEn:"Muritiba Park",nome:"Parque da Muritiba (sem carro)",pt:"O Parque Municipal da Muritiba fica dentro da cidade de Lençóis. Damos a volta ao Parque passando por: Piscinas do Serrano, Poço Halley, Salões de areias coloridas, Cachoeira da Primavera, Mirante de Lençóis e Cachoeirinha.\nSaída: 9:30h | Retorno: 16h | Total: 5km",en:"Muritiba Municipal Park is located within the town of Lençóis. This tour loops through the park and includes several attractions: Serrano natural pools, Halley Pool, the colorful sand caves, Primavera Waterfall, the Lençóis lookout point, and Cachoeirinha.\nDeparture: 9:30 AM\nReturn: 4:00 PM\nTotal hike: 5 km",taxa:20,fotos:["13XFhhDyH-3BIM9bZGFxWa4qwqBF8TsXd"],c4:180,c8:360,ag:{3:180,4:180,5:180,6:180,7:360,8:360,9:360,10:360,11:360,12:360,13:540,14:540,15:540,16:540}},
  {id:5,nomeEn:"Pantanal Marimbus + Roncador River",nome:"Pantanal Marimbus + Rio Roncador",pt:"Saimos de Lençóis às 8:30 por 40 minutos até a Comunidade Quilombola do Remanso. Pegamos o barco para descer o rio em meio a Palmeiras de Licuri e espelhos d'água magníficos. Após 1 hora de remada, caminhamos 30 minutos até as piscinas naturais do Rio Roncador.\nSaída: 8:30 | Retorno: 17h | Total 6km",en:"We leave Lençóis at 8:30 AM and drive for 40 minutes to the Quilombola Community of Remanso. From there, we take a guided canoe ride down the river, passing through licuri palm forests and stunning water mirrors. After about an hour of paddling, we hike 30 minutes to the natural pools of the Roncador River, perfect for swimming. In the afternoon, we have lunch at Dona Val's riverside restaurant. At the end of the day, we hike 40 minutes back to the car for our return.\nDeparture: 8:30 AM\nReturn: 5:00 PM\nTotal hike: 6 km",taxa:40,fotos:["1THQUibv8X_Rv8Z7IMFe3uF5vEwQnKyGQ"],c4:200,c8:400,ag:{3:530,4:530,5:700,6:730,7:1060,8:1060,9:1230,10:1400,11:1430,12:1460,13:1590,14:1590,15:1590,16:1590}},
  {id:6,nomeEn:"Fumaça Waterfall from Above + Riachinho",nome:"Cachoeira da Fumaça + Riachinho",pt:"Saída de Lençóis por 1h30m de carro até o início da trilha da Fumaça. Ida e volta somam 12km. Chegaremos na visão da Fumaça por cima, a maior cachoeira do Brasil. Ao fim do dia, pôr do sol no Riachinho.\nSaída: 8h | Retorno: 18h | Total 12km",en:"We leave Lençóis by car for a 1.5-hour drive to the start of the Fumaça trail. The round-trip hike is 12 km, with the first 2 km being a steep uphill climb, followed by 4 km of flat terrain on rocky ground. The view from the top of Brazil's tallest waterfall is breathtaking. We end the day watching the sunset at Riachinho.\nDeparture: 8:00 AM\nReturn: 6:00 PM\nTotal hike: 12 km",taxa:20,fotos:[],c4:270,c8:540,ag:{3:700,4:700,5:850,6:1000,7:1400,8:1400,9:1550,10:1700,11:1850,12:2000,13:2100,14:2100,15:2100,16:2100}},
  {id:7,nomeEn:"Blue and Enchanted Pool",nome:"Poço Azul e Poço Encantado",pt:"Saída por 2 horas de carro até o Poço Encantado (60m, sem banho, proibido menores de 12 anos). Depois seguimos para o Poço Azul, onde mergulhamos com snorkel e colete fornecidos.\nSaída 8:30 | Retorno 17h | Total 1km",en:"We drive for 2 hours to Poço Encantado, a stunning 60-meter-deep crystal-clear pool where swimming is not allowed, and children under 12 are not permitted. We then continue to Poço Azul, where we can swim and float with provided snorkels and life vests.\nDeparture: 8:30 AM\nReturn: 5:00 PM\nTotal hike: 1 km",taxa:124.5,fotos:["1zsswRfj2i2QQya5ys8G3e4Dups0HkKTo"],c4:250,c8:500,ag:{3:630,4:630,5:800,6:930,7:1260,8:1260,9:1890,10:1890,11:1890,12:1890,13:2520,14:2520,15:2520,16:2520}},
  {id:8,nomeEn:"Sossego Waterfall",nome:"Cachoeira do Sossego + Ribeirão do Meio (sem carro)",pt:"Trilha que começa dentro de Lençóis, com passagens no leito do rio e dentro de um cânion até a Cachoeira do Sossego (60m). No retorno, paramos no Ribeirão do Meio, o tobogã natural da Chapada.",en:"The trail starts within the town of Lençóis. This is a scenic hike through rocky riverbeds and a narrow canyon leading to the 60-meter-high Sossego Waterfall, which has a large pool for swimming. On the way back, we stop at Ribeirão do Meio, a natural waterslide made of quartz.",taxa:0,fotos:[],c4:250,c8:500,ag:{3:250,4:250,5:500,6:500,7:500,8:500,9:750,10:750,11:750,12:750,13:1000,14:1000,15:1000,16:1000}},
  {id:9,nomeEn:"Vale do Pati 3-Day Trek",nome:"Vale do Pati 3 dias",pt:"Roteiro circular no Trekking mais visitado do Brasil. 3 dias trilhando entre grutas, mirantes e cachoeiras, dormindo na casa dos nativos. Saímos de Lençóis às 7h de carro por 2 horas até a vila da Guiné. Incluso: guia, transporte, hospedagem nas casas dos nativos e toda a comida.",en:"A circular trekking route through Brazil's most famous hiking trail. Over 3 days, we hike among caves, lookouts, and waterfalls, far from phone signals, and sleep in the homes of locals. We leave Lençóis at 7:00 AM and drive for 2 hours to Guiné village, where the trek begins.\nIncluded: local guide, round-trip transportation, accommodation in local homes, and all meals prepared by the hosts.",taxa:0,fotos:[],c4:960,c8:1920,ag:{3:1600,4:1600,5:3200,6:3200,7:3200,8:3200,9:4800,10:4800,11:4800,12:4800,13:6400,14:6400,15:6400,16:6400}},
  {id:10,nomeEn:"Buracão Waterfall",nome:"Cachoeira do Buracão",pt:"Saindo de Lençóis, são 4 horas de viagem até Ibicoara para visitar a Cachoeira do Buracão. Para chegarmos até a imponente queda de 90 metros, nadamos em uma fenda mágica com coletes fornecidos.\nTotal 6km",en:"We drive 4 hours by car to Ibicoara to visit Buracão Waterfall. To reach the imposing 90-meter-high Buracão Waterfall, we swim through a magical canyon (life jackets provided). For the adventurous, it's also possible to rappel the entire height.\nTotal hike: 6 km",taxa:30,fotos:["1RAWUnQj36OQ_fMhx4pvmZSDlypi3HoFc"],c4:300,c8:600,ag:{3:700,4:700,5:1000,6:1000,7:1400,8:1400,9:2100,10:2100,11:2100,12:2100,13:2800,14:2800,15:2800,16:2800}},
  {id:11,nomeEn:"Fumacinha Waterfall",nome:"Cachoeira da Fumacinha",pt:"Localizada em Ibicoara, trilha técnica e incrível acompanhando o leito do rio com várias cachoeiras até chegar na Fumacinha com 105 metros de altura, dentro de um cânion fechado parecendo um Santuário.\nTotal 18km",en:"Located in the town of Ibicoara, this is one of the most impressive waterfalls in the Chapada Diamantina. The trail follows the riverbed through diverse landscapes and smaller waterfalls, ending at the 105-meter-high Fumacinha inside a narrow canyon that resembles a cathedral. With some luck, you may witness a natural concert of swallows circling the falls.\nTotal hike: 18 km",taxa:0,fotos:["1u0Kgjh_IPmSNUTQtl-wmR06n5o8ThCh2"],c4:360,c8:720,ag:{3:700,4:700,5:1000,6:1000,7:1400,8:1400,9:2100,10:2100,11:2100,12:2100,13:2800,14:2800,15:2800,16:2800}},
  {id:12,nomeEn:"Pati Valley",nome:"Vale do Pati",pt:"Roteiro no Trekking mais visitado do Brasil. Trilhando entre grutas, mirantes e cachoeiras, sem sinal, dormindo na casa dos nativos. Saímos de Lençóis às 7h de carro por 2 horas até a vila da Guiné. Incluso: guia, transporte, hospedagem e toda a comida preparada pelos nativos!",en:"Trekking through Brazil's most famous trail, between caves, lookouts, and waterfalls, far from signal and immersed in nature. We leave Lençóis at 7:00 AM and drive for 2 hours to the village of Guiné, where the adventure begins.\nIncluded: local guide, round-trip transportation, lodging in local homes, and all meals prepared by the hosts.",taxa:0,fotos:[],c4:320,c8:640,ag:{3:533,4:533,5:1067,6:1067,7:1067,8:1067,9:1600,10:1600,11:1600,12:1600,13:2133,14:2133,15:2133,16:2133}},
  {id:13,nomeEn:"Águas Claras",nome:"Águas Claras",pt:"Saída de Lençóis por 30 minutos de carro até o início da trilha. Ida e volta somam 18km, todos planos e entre o Vale dos 3 Irmãos, com um visual magnífico. Chegaremos nas piscinas naturais de água cristalina de frente para o Morrão.",en:"Departure from Lençóis with a 30-minute drive to the trailhead. The round-trip hike covers 18 km, all on flat terrain, through the stunning Vale dos Três Irmãos (Valley of the Three Brothers), offering magnificent views.\nWe'll reach the crystal-clear natural pools, facing the Morrão, one of the most iconic and impressive mountains in the Chapada Diamantina.",taxa:0,fotos:[],c4:270,c8:540,ag:{3:630,4:630,5:800,6:800,7:1260,8:1260,9:1430,10:1600,11:1600,12:1600,13:1890,14:1890,15:1890,16:1890}},
  {id:14,nomeEn:"Day Off",nome:"Dia Livre",pt:"Sem roteiro programado. Dia para descanso, exploração independente da cidade histórica de Lençóis, compras de artesanato local ou banho no Rio Lençóis.",en:"No itinerary scheduled. A free day to rest, explore the historic town of Lençóis, shop for local handicrafts, or swim in the Lençóis River.",taxa:0,fotos:[],c4:0,c8:0,ag:{3:0,4:0,5:0,6:0,7:0,8:0,9:0,10:0,11:0,12:0,13:0,14:0,15:0,16:0}},
  {id:15,nomeEn:"Conceição dos Gatos and Lagoa dos Patos",nome:"Conceição dos Gatos e Lagoa dos Patos",pt:"Imersão na tranquilidade da Chapada Diamantina passando por pequenas comunidades rurais. Seguimos até a Lagoa dos Patos, uma pequena cachoeira com águas calmas e cristalinas, perfeita para um banho refrescante.\nTotal 3km",en:"This tour is a true immersion in the tranquility and natural beauty of the Chapada Diamantina. The route passes through small rural communities surrounded by hills, rivers, and abundant native vegetation. In Conceição dos Gatos, visitors experience the charm of a typical village of the region, with its simple houses, welcoming residents, and peaceful atmosphere. We then continue to Lagoa dos Patos, a small waterfall with calm, crystal-clear waters — perfect for a refreshing swim. Along the way, it's possible to enjoy beautiful landscapes, observe birds, and take in the silence of nature.\nTotal: 3 km",taxa:20,fotos:[],c4:300,c8:600,ag:{3:600,4:600,5:null,6:null,7:null,8:null,9:null,10:null,11:null,12:null,13:null,14:null,15:null,16:null}},
  {id:16,nomeEn:"Rodas and Rio Preto",nome:"Rodas e Rio Preto",pt:"Trilha leve cercada por vegetação nativa até o Rio Preto, rio de águas escuras perfeito para um banho. O passeio passa pela comunidade de Rodas, onde o visitante pode conhecer um pouco da vida simples e acolhedora dos moradores locais.\nInício 9h | Fim 17h | Total 8km",en:"This trail combines stunning landscapes, river swimming, and the charm of local communities. The route follows gentle paths surrounded by native vegetation and leads to the Rio Preto, a dark-water river perfect for a refreshing swim. Along the way, you can admire panoramic views, small waterfalls, and rock formations typical of the region. The tour also passes through the community of Rodas, where visitors can experience a bit of the simple and welcoming lifestyle of the local residents.\nStart: 9:00 AM\nEnd: 5:00 PM\nTotal: 8 km",taxa:0,fotos:[],c4:300,c8:600,ag:{3:600,4:600,5:null,6:null,7:null,8:null,9:null,10:null,11:null,12:null,13:null,14:null,15:null,16:null}},
  {id:17,nomeEn:"Torrinha Cave, Pratinha Farm and Camelo Hill",nome:"Caverna Torrinha, Fazenda Pratinha e Morro do Camelo",pt:"Viagem de 1h30 até a Caverna da Torrinha, caminhada guiada de 1h30 explorando flores de aragonita e agulhas de gipsita. Seguimos 20 minutos até a Fazenda Pratinha. No retorno, parada no Mirante do Camelo.\nSaída: 8h30 | Retorno: 18h | Total 2km",en:"We will leave Lençóis on a 1.5-hour trip to Torrinha Cave, where we will take a 1.5-hour guided walk exploring impressive formations such as aragonite flowers and gypsum needles. Next, we will continue for another 20 minutes to Pratinha Farm, an underground water spring with crystal-clear waters in the heart of the Bahian hinterland. On the way back, we will stop at the Camelo Lookout to enjoy the view before returning to Lençóis.\nDeparture: 8:30 AM\nReturn: 6:00 PM\nTotal distance: 2 km",taxa:170,fotos:[],c4:null,c8:0,ag:{3:500,4:500,5:700,6:null,7:null,8:null,9:null,10:null,11:null,12:null,13:null,14:null,15:null,16:null}},
  {id:18,nomeEn:"UVVA Winery",nome:"Vinícola UVVA",pt:"Sairemos de Mucugê por volta de 11h por 1 hora de carro para a experiência de degustação dos vinhos da Vinícola UVVA. Opção de restaurante para almoço. No final do dia retornaremos a Lençóis.",en:"We leave Mucugê at around 11:00 AM for a 1-hour drive to UVVA Winery for a wine tasting experience. There is also a restaurant option for lunch. We return to Lençóis at the end of the day.",taxa:0,fotos:[],c4:null,c8:0,ag:{3:600,4:600,5:null,6:null,7:null,8:null,9:null,10:null,11:null,12:null,13:null,14:null,15:null,16:null}},
  {id:19,nomeEn:"Lapa Doce Cave, Vale das Piscinas & Morro do Camelo",nome:"Lapa Doce, Vale das Piscinas e Morro do Camelo",pt:"Nos deslocamos por 1h30 até a Gruta da Lapa Doce. Caminhamos 40 minutos dentro da caverna. Seguimos para o Vale das Piscinas no Rio Mucugezinho. Finalizamos o dia no Morro do Camelo, um mirante surpreendente com lindo pôr do sol.\nSaída: 08:30 | Retorno: 18:00 | Total: 2km",en:"We drive for about 1.5 hours to reach Lapa Doce Cave, one of the largest limestone caves in the Chapada Diamantina. Inside the cave, we walk for around 40 minutes, admiring the impressive formations of stalactites and stalagmites. Next, we continue to Vale das Piscinas, on the Mucugezinho River, where we enjoy the natural pools and have lunch at a riverside restaurant (not included). We finish the day at Morro do Camelo, a surprising and little-known viewpoint, perfect for enjoying a beautiful sunset.\nDeparture: 08:30\nReturn: 18:00\nTotal hiking distance: 2 km",taxa:56,fotos:["1F9zokJ4BndT_1gDth75NTBkE3YIsfmI4"],c4:null,c8:0,ag:{3:580,4:580,5:700,6:780,7:1160,8:1160,9:null,10:null,11:null,12:null,13:null,14:1740,15:1740,16:null}},
  {id:20,nomeEn:"Horseback Riding Tour",nome:"Passeio a Cavalo",pt:"Vamos cavalgar por 9km atravessando córregos lindíssimos, em um caminho de terra quase todo sombreado. Fazemos uma parada na beira do Rio Capivara para banho e lanche. Jordélio, o responsável, acompanha o tempo todo.",en:"We will ride for about 9 km, crossing beautiful streams along a dirt trail that is mostly shaded. We stop by the Capivara River, where we can swim and enjoy a snack. After the break, we return to the starting point. Before the ride, we receive instructions on how to mount and guide the horse. Jordélio, the guide responsible for the activity, accompanies the group the entire time.",taxa:0,fotos:[],c4:null,c8:0,ag:{3:400,4:800,5:1200,6:1600,7:4000,8:4400,9:null,10:null,11:null,12:null,13:null,14:null,15:null,16:null}}
];

const HOSP = [
  {id:1,nomeEn:"Mosquito Waterfall, Devil's Pool, and Pai Inacio Hill",nome:"Pousada Pouso da Trilha",local:"Lençóis",s:282,c:332,t:298,g:0},
  {id:2,nomeEn:"Lapa Doce Cave + Pratinha Farm",nome:"Hotel Canto das Águas",local:"Lençóis",s:0,c:0,t:1751,g:0},
  {id:3,nomeEn:"Buracão + Fumacinha + Poços",nome:"Pousada Recanto dos Mineiros",local:"Lençóis",s:160,c:200,t:270,g:0},
  {id:4,nomeEn:"Muritiba Park",nome:"Pousada Kabana de Pedra",local:"Ibicoara",s:135,c:200,t:330,g:45},
  {id:5,nomeEn:"Pantanal Marimbus + Roncador River",nome:"Agnaldo",local:"Pati",s:200,c:400,t:600,g:0},
  {id:6,nomeEn:"Fumaça Waterfall from Above + Riachinho",nome:"Casa de Dona Bia",local:"Ibicoara",s:170,c:340,t:510,g:0},
  {id:7,nomeEn:"Blue and Enchanted Pool",nome:"Pousada Mucugê",local:"Mucugê",s:180,c:290,t:360,g:100},
  {id:8,nomeEn:"Sossego Waterfall",nome:"Pousada Monte Azul",local:"Mucugê",s:0,c:330,t:0,g:100},
  {id:9,nomeEn:"Vale do Pati 3-Day Trek",nome:"Igrejinha",local:"Pati",s:200,c:400,t:600,g:0},
  {id:10,nomeEn:"Buracão Waterfall",nome:"Zé Preto",local:"Pati",s:230,c:460,t:690,g:0},
  {id:11,nomeEn:"Fumacinha Waterfall",nome:"Dona Linda",local:"Pati",s:215,c:430,t:645,g:0},
  {id:12,nomeEn:"Pati Valley",nome:"Pousada Vila Serrano",local:"Lençóis",s:406,c:451,t:667,g:0},
  {id:13,nomeEn:"Águas Claras",nome:"Seu Eduardo",local:"Pati",s:230,c:460,t:690,g:0},
  {id:14,nomeEn:"Day Off",nome:"Casa da VAL",local:"Ibicoara",s:170,c:340,t:510,g:0},
  {id:15,nomeEn:"Conceição dos Gatos and Lagoa dos Patos",nome:"Pousada do Jairo",local:"Ibicoara",s:180,c:250,t:345,g:0},
  {id:16,nomeEn:"Rodas and Rio Preto",nome:"Prefeitura",local:"Pati",s:230,c:460,t:690,g:0},
  {id:17,nomeEn:"Torrinha Cave, Pratinha Farm and Camelo Hill",nome:"Pousada To em Casa",local:"Lençóis",s:175,c:210,t:295,g:0},
  {id:18,nomeEn:"UVVA Winery",nome:"Hotel de Lençóis",local:"Lençóis",s:490,c:600,t:987,g:0},
  {id:19,nomeEn:"Lapa Doce Cave, Vale das Piscinas & Morro do Camelo",nome:"Refúgio na Serra",local:"Mucugê",s:1580,c:1580,t:0,g:0},
  {id:20,nomeEn:"Horseback Riding Tour",nome:"— Sem hospedagem —",local:"",s:0,c:0,t:0,g:0}
];

